server:
  port: 8088
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: ms-pagos
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/db_pago?useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html
logging:
  file:
    name: log-pagos.log
  level:
    gym.ms_pago: DEBUG
    org.hibernate.SQL: DEBUG
    root: INFO